#!/bin/bash
PS1="\[\033[38;2;255;255;0m\]\[\033[93m\][\T][\u@\h:\w]> \[$(tput sgr0)\]"
alias vi="vim"
alias r="ranger"
alias qv="qview"
alias m="make"
alias mt="make tc"
alias smi="sudo make install"
alias msmi="make && sudo make install"
alias l="ls -CF"
alias la="ls -A"
alias ll="ls -alF"
alias ls="ls --color=auto"
alias wine='PULSE_LATENCY_MSEC=60 wine'
